name: GrapplingHook
author: mSuro_
description: A simple grappling hook plugin. Heavily modified fork of GrapplingHook by snowgears [65000+ downloads]
version: 1.0
api-version: 1.17
main: me.msuro.grapplinghook.GrapplingHook
permissions:
    grapplinghook.pull.self:
        description: Allows player to pull themselves to a location
        default: op
    grapplinghook.pull.mobs:
        description: Allows player to pull mobs with the hook
        default: op
    grapplinghook.pull.players:
        description: Allows player to pull players with the hook
        default: op
    grapplinghook.pull.items:
        description: Allows player to pull items with the hook
        default: op
    grapplinghook.operator:
        description: Allows player to use commands for plugin
        default: op
    grapplinghook.player.nopull:
        description: Player can not be pulled by other players
        default: op
    grapplinghook.player.nocooldown:
        description: Player ignores grapple cooldown
        default: op
